version: "3"
services:
  app:
    image: "backend-distri"
    ports:
      - "1818:1818"
    environment:
      SPRING_DATABASE_CONNECTION: jdbc:postgresql://localhost:5432/Distribuidos?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_USERNAME: Distribuidos
      PASSWORD: Distribuidos
  db:
    network_mode: "host"
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata #primera parte es el disco duro del servidor, segunda parte es donde se encuentra la data dentro del contenedor.
    environment:
      POSTGRES_DB: Distribuidos
      POSTGRES_USER: Distribuidos
      POSTGRES_PASSWORD: Distribuidos
      PGDATA: /var/lib/postgresql/data/pgdata
#     networks:
#       - distribuidos
# networks:
#   resolute:
#     external:
#       name: distribuidos
