version: '3'

services:
  app:
    image: "backend-distri"
    ports:
      - "1818:1818"
    depends_on:
      - db

  db:
    image: "postgres:10.4"
    environment:
      POSTGRES_USER: Distribuidos
      POSTGRES_PASSWORD: Distribuidos
      POSTGRES_DB: Distribuidos
    ports:
      - "5432:5432"